// @mostajs/replica-monitor — scaffoldMonitorService
// Author: Dr Hamid MADANI drmdh@msn.com
// License: AGPL-3.0-or-later
//
// Emits a ready-to-run services/monitor.mjs into a target project. The
// emitted file loads .env + .mostajs/config.env, reads the replicator-tree
// (no DB connections needed), and starts the HTTP dashboard.

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

export interface MonitorScaffoldOptions {
  projectDir?:  string;
  servicePath?: string;
  dryRun?:      boolean;
  force?:       boolean;
}

export interface MonitorScaffoldResult {
  wrote:   boolean;
  path:    string;
  action:  'created' | 'skipped (exists)' | 'overwritten' | 'dry-run';
  content: string;
}

export function scaffoldMonitorService(opts: MonitorScaffoldOptions = {}): MonitorScaffoldResult {
  const projectDir  = resolve(opts.projectDir ?? process.cwd());
  const servicePath = opts.servicePath ?? 'services/monitor.mjs';
  const target      = resolve(projectDir, servicePath);
  const content     = buildTemplate();

  if (opts.dryRun) return { wrote: false, path: target, action: 'dry-run', content };

  const exists = existsSync(target);
  if (exists && !opts.force) {
    return { wrote: false, path: target, action: 'skipped (exists)', content };
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, 'utf8');
  return {
    wrote: true,
    path:  target,
    action: exists ? 'overwritten' : 'created',
    content,
  };
}

function buildTemplate(): string {
  return `#!/usr/bin/env node
// services/monitor.mjs — generated by @mostajs/replica-monitor scaffold.
// Read-only live dashboard that watches .mostajs/replicator-tree.json
// and renders replicas + CDC rules + activity events in a browser.
//
// Runs without DB connections — purely from the tree file.
//
//   npm run monitor
//   # or : node services/monitor.mjs
//
// Config via env :
//   MONITOR_PORT           default 14499
//   MONITOR_HOST           default 127.0.0.1
//   MONITOR_TOKEN          optional Bearer auth
//   MONITOR_TREE           default .mostajs/replicator-tree.json
//   MONITOR_POLL_MS        default 2000

import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// --- Env loading ---
const loadEnv = (p) => {
  if (!existsSync(p)) return;
  for (const line of readFileSync(p, 'utf8').split('\\n')) {
    if (!line || line.startsWith('#') || !line.includes('=')) continue;
    const i = line.indexOf('=');
    const k = line.slice(0, i).trim();
    const v = line.slice(i + 1).trim();
    if (process.env[k] === undefined) process.env[k] = v;
  }
};
loadEnv(resolve('.mostajs/config.env'));
loadEnv(resolve('.env'));

const PORT  = Number(process.env.MONITOR_PORT ?? 14499);
const HOST  = process.env.MONITOR_HOST ?? '127.0.0.1';
const TOKEN = process.env.MONITOR_TOKEN || undefined;
const TREE  = resolve(process.env.MONITOR_TREE ?? '.mostajs/replicator-tree.json');
const POLL  = Number(process.env.MONITOR_POLL_MS ?? 2000);

const { startMonitor, readTreeManager } = await import(resolve('node_modules/@mostajs/replica-monitor/dist/index.js'));

const manager = readTreeManager({ tree: TREE });

const handle = await startMonitor({
  manager,
  port:      PORT,
  host:      HOST,
  authToken: TOKEN,
  pollMs:    POLL,
});

const auth = TOKEN ? \`?token=\${TOKEN}\` : '';
console.log(\`\\n  ▶ replica-monitor running at \${handle.url}\${auth}\`);
console.log(\`    watching \${TREE}\\n    press Ctrl+C to stop.\\n\`);

const shutdown = async (sig) => {
  console.log(\`\\n[monitor] shutting down (\${sig})\`);
  try { await handle.stop(); } catch {}
  try { manager.stop?.(); } catch {}
  process.exit(0);
};
process.on('SIGINT',  () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));
`;
}
